SELECT * FROM RETAIL_SALES ;

-- NULL value check: No NULL values were found in the table.

SELECT  
	SUM(CASE WHEN ROW_ID 		IS NULL THEN 1 ELSE 0 end) AS row_id,
	SUM(CASE WHEN ORDER_ID 		IS NULL THEN 1  ELSE 0 END) order_id,
	SUM(CASE WHEN ORDER_DATE 	IS NULL THEN 1  ELSE 0 END) order_Date,
	SUM(CASE WHEN SHIP_DATE 	IS NULL THEN 1  ELSE 0 END) ship_date,
	SUM(CASE WHEN SHIP_MODE		IS NULL THEN 1  ELSE 0 END) shipmode,
	SUM(CASE WHEN CUSTOMER_ID 	IS NULL THEN 1  ELSE 0 END) customerid,
	SUM(CASE WHEN CUSTOMER_NAME IS NULL THEN 1  ELSE 0 END) CUSTOMER_NAME ,
	SUM(CASE WHEN COUNTRY 		IS NULL THEN 1  ELSE 0 END) COUNTRY ,
	SUM(CASE WHEN CITY 			IS NULL THEN 1  ELSE 0 END) CITY ,
	SUM(CASE WHEN STATE 		IS NULL THEN 1  ELSE 0 END) STATE ,
	SUM(CASE WHEN REGION 		IS NULL THEN 1  ELSE 0 END) REGION ,
	SUM(CASE WHEN PRODUCT_ID 	IS NULL THEN 1  ELSE 0 END) PRODUCT_ID ,
	SUM(CASE WHEN CATEGORY 		IS NULL THEN 1 ELSE 0 END) CATEGORY ,
	SUM(CASE WHEN SUB_CATEGORY 	IS NULL THEN 1  ELSE 0 END) SUB_CATEGORY ,
	SUM(CASE WHEN PRODUCT_NAME 	IS NULL THEN 1  ELSE 0 END) PRODUCT_NAME ,
	SUM(CASE WHEN SALES 		IS NULL THEN 1 ELSE 0 END) SALES ,
	SUM(CASE WHEN QUANTITY 		IS NULL THEN 1  ELSE 0 END) QUANTITY ,
	SUM(CASE WHEN DISCOUNT 		IS NULL THEN 1  ELSE 0 END) DISCOUNT ,
	SUM(CASE WHEN PROFIT 		IS NULL THEN 1 ELSE 0 END) PROFIT ,
	SUM(CASE WHEN POSTAL_CODE 	IS NULL THEN 1 ELSE 0 END) POSTAL_CODe
FROM RETAIL_SALES ;

-- Checking duplicates using the RANK function

SELECT *
FROM (
	SELECT
		rs.*,
		ROW_NUMBER () OVER (PARTITION BY ORDER_ID , ORDER_DATE , SHIP_DATE ,
		SHIP_MODE ,	CUSTOMER_ID ,CUSTOMER_NAME ,
		COUNTRY , CITY , STATE ,	REGION ,
		PRODUCT_ID , CATEGORY ,	SUB_CATEGORY ,
		PRODUCT_NAME ,	SALES ,QUANTITY ,	DISCOUNT ,
		PROFIT , POSTAL_CODE ORDER BY ROW_ID ) AS rn
	FROM RETAIL_SALES rs 
	) Duplicates
WHERE rn > 1;

--Removing duplicate records

DELETE FROM retail_sales
WHERE ROW_ID IN (
	SELECT ROW_ID
    FROM (
        SELECT 
            ROW_ID,
            ROW_NUMBER() OVER (
                PARTITION BY
                    ORDER_ID , ORDER_DATE , SHIP_DATE ,
                    SHIP_MODE , CUSTOMER_ID , CUSTOMER_NAME ,
                    COUNTRY , CITY , STATE , REGION ,
                    PRODUCT_ID , CATEGORY , SUB_CATEGORY ,
                    PRODUCT_NAME , SALES , QUANTITY , DISCOUNT ,
                    PROFIT , POSTAL_CODE
                ORDER BY ROW_ID
            ) rn
        FROM retail_sales
    )
    WHERE rn > 1
);



